### ISSUE TITLE
Codecov misses files when paths have names that are repeated

### ISSUE THREAD

**Issue by rohan-at-sentry** [codecov/engineering-team#1646] opened 2024-04-23 14:29 UTC
**Describe the bug**
Whenever we encounter files with paths that have names that are repeated (some examples will follow below), codecov's path fixing/matching pieces do not gracefully handle that condition, causing coverage for those files to be missing from Codecov's reporting entirely.

**Expected behavior**
Files with coverage should show on Codecov
**Screenshots**

**Environments**
Customers reporting this have been using Kotlin/Java, but we're not entirely sure if this is a Java/Kotlin only problem.

**Additional context**
Linked Issues

- https://github.com/codecov/feedback/issues/321#issuecomment-2051802310
    - path there is `/dzirbel/kotify/tree/993f04d04cd019479e8c100acd91a5e2f14c4847/repository/src/main/kotlin/com/dzirbel/kotify/repository`
- https://github.com/codecov/feedback/discussions/345
    - path there is `shardingsphere\infra\binder\src\main\java\org\apache\shardingsphere\infra\binder\segment\expression\ExpressionSegmentBinder.java`

**Comment by michelletran-sentry** [comment] 2024-12-17 19:42
I've confirmed that this is still happening in recent Java repos. The files paths are missing entirely from the generated report object in GCS.

**Comment by michelletran-sentry** [comment] 2024-12-17 21:38
Looking at some missing files and their raw XML, it appears that they are missing coverage information in the raw XML that gets provided. 

For instance, a whole directory is missing [in Codecov](https://app.codecov.io/github/apache/shardingsphere/tree/master/infra%2Fbinder%2Fsrc%2Fmain%2Fjava%2Forg%2Fapache%2Fshardingsphere%2Finfra%2Fbinder%2Fcontext?displayType=tree), a whole directory (`shardingsphere/infra/binder/context/aware`) is missing, that is in the [main repo](https://github.com/apache/shardingsphere/tree/master/infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/aware). Looking at the uploaded XML, it looks like the that section is declared in the `jacoco.xml`, but it doesn't contain any coverage information.

This is what I see in the XML (truncated):

```XML
  <package name="org/apache/shardingsphere/infra/binder/context/aware">
    <class name="org/apache/shardingsphere/infra/binder/context/aware/ParameterAware" sourcefilename="ParameterAware.java"/>
    <class name="org/apache/shardingsphere/infra/binder/context/aware/CursorAware" sourcefilename="CursorAware.java"/>
    <sourcefile name="CursorAware.java"/>
    <sourcefile name="ParameterAware.java"/>
  </package>
```

**Comment by michelletran-sentry** [comment] 2024-12-17 21:41
Oh nvm, those are interfaces, so they wouldn't need to be covered with coverage 🤦

**Comment by michelletran-sentry** [comment] 2024-12-18 18:09
It looks like the problems with `shardingsphere` is no longer happening (they changed their file structure slightly, not sure if that's the cause). I also tried recreating the report for `kotify` and was able to get the missing files in the report. They haven't updated in 3 months, so might not have picked up latest changes to the `jacoco` processor. I'm going to close this ticket, as I'm not sure if there's still an issue related to Jacoco file path matching. Feel free to reopen this ticket or link this ticket to a new one if we find more of these errors.

**Closed as completed by michelletran-sentry** 2024-12-18 18:09 UTC
Labels: bug, Medium, Area: Report Upload
